version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
    
  php:
    build:
      context: .
    container_name: php
    ports:
      - "9003:9003"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banco_dados_1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
      
volumes:
  pgdata: